#!/bin/bash

#acquire the parameters
for v
do
    if [[ "$v" == "-u" ]]
        then
        #if -u is a parameter then ono = 1 means capitals
            ono=1
    elif [[ "$v" == "-n" ]]
        then
        #store -n parameter
            duo=$v
    elif [[ "$v" -ge 0 ]]
        then
        #store the shift value
            a=$v
fi
done

#create an array of letters in the alphabetical order
letters=(a b c d e f g h i j k l m n o p q r s t u v w x y z)

#make the pattern
message=[${letters[$a]}-za-${letters[$((a-1))]}]

#Checks if should be printed in capitals
if [[ $ono -eq 1 ]]; then
    #print in capitals
	echo $message | tr '[a-z]' '[A-Z]'
	else
	echo $message
fi