#!/bin/bash

#uppercase=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
c=1
while [ $c -le 25 ]
do
	transition=$(./create_pattern -n $c -u)
	echo "Shift $c"
	cat $1 | tr '[A-Z]' $transition
c=$(( $c + 1 ))
done
